jQuery(function() {
    $("#modal_cliente").dialog({
        autoOpen:false,
        height:350,
        width:450,
        resizable:false,
        closeOnEscape:false,
        modal:true,
        buttons:{
            "Cerrar":function(){
                $(this).dialog("close");
            }
        }
    });
    $("#modal_contratante").dialog({
        autoOpen:false,
        height:350,
        width:450,
        resizable:false,
        closeOnEscape:false,
        modal:true,
        buttons:{
            "Cerrar":function(){
                $(this).dialog("close");
            }
        }
    });
    $("#modal_gerente").dialog({
        autoOpen:false,
        height:350,
        width:450,
        resizable:false,
        closeOnEscape:false,
        modal:true,
        buttons:{
            "Cerrar":function(){
                $(this).dialog("close");
            }
        }
    });
    $("#modal_supervisor").dialog({
        autoOpen:false,
        height:350,
        width:450,
        resizable:false,
        closeOnEscape:false,
        modal:true,
        buttons:{
            "Cerrar":function(){
                $(this).dialog("close");
            }
        }
    });
    $("#modal_proveedor").dialog({
        autoOpen:false,
        height:350,
        width:450,
        resizable:false,
        closeOnEscape:false,
        modal:true,
        buttons:{
            "Cerrar":function(){
                $(this).dialog("close");
            }
        }
    });
    /**
     * MODAL PARAMETROS PRESUPUESTO
     * DE VENTAS
     */
    $("#div-modal-pptoventa").dialog({
        autoOpen:false,
        heigh:950,
        width:550,
        resizable:false,
        closeOnEscape:false,
        modal:true,
        buttons:{
            "Cerrar":function(){
                $(this).dialog("close");
            }
        }
    });
})